// Class automatically generated by Dev-C++ New Class wizard

#include "huffmancoder.h" // class's header file

// class constructor
HuffmanCoder::HuffmanCoder()
{
	// insert your code here
}

// class destructor
HuffmanCoder::~HuffmanCoder()
{
	// insert your code here
}