// Class automatically generated by Dev-C++ New Class wizard

#ifndef HUFFMANCODER_H
#define HUFFMANCODER_H

#include "huffmantree.h"

using namespace huffman;

// ¹ş·òÂü±àÂë½âÂëÆ÷Àà
class HuffmanCoder
{
	public:
		// class constructor
		HuffmanCoder();
		// class destructor
		~HuffmanCoder();
};

#endif // HUFFMANCODER_H

